version: '3.7'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: { { cookiecutter.postgres_user } }
      POSTGRES_PASSWORD: { { cookiecutter.postgres_password } }
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port {{cookiecutter.backend_port}}
    ports:
      - '{{cookiecutter.backend_port}}:{{cookiecutter.backend_port}}'
    volumes:
      - ./backend/:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://{{cookiecutter.postgres_user}}:{{cookiecutter.postgres_password}}@db/{{cookiecutter.postgres_user}}'
      FRONTEND_SERVER_URL: 'http://localhost:{{cookiecutter.frontend_port}}'
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:cached'
    ports:
      - '{{cookiecutter.frontend_port}}:3000'
    environment:
      - NODE_ENV=development

volumes:
  db-data:
