version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - {{cookiecutter.port}}:80
    restart: always
    networks:
      - nginx-network

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: {{cookiecutter.postgres_user}}
      POSTGRES_PASSWORD: {{cookiecutter.postgres_password}}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8888
    ports:
      - '8888:8888'
    volumes:
      - ./backend/:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://{{cookiecutter.postgres_user}}:{{cookiecutter.postgres_password}}@db/{{cookiecutter.postgres_user}}'
      FRONTEND_SERVER_URL: 'http://localhost:{{cookiecutter.port}}'
    networks:
      - nginx-network
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    networks:
      - nginx-network

networks:
  nginx-network:

volumes:
  db-data:
