version: 2.1

machine:
  services:
    - docker

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: sudo pip install cookiecutter
      - run:
          command: ./test.sh
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
